version : '2'

services:
  zookeeper :
    image: zookeeper:3.8.1
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka :
    image: wurstmeister/kafka
    container_name: kafka
    ports: # ????:????????
      - "9092:9092"
    environment: # kafka Broker ???? ??
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 # kafka? zookeeper? ????? ?? ??? ??
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
